CREATE DATABASE sp_rec;

USE sp_rec; 

CREATE TABLE std_info (ID VARCHAR(50) PRIMARY KEY,F_name VARCHAR(50),L_name VARCHAR(50),Pasword VARCHAR(50),Gender VARCHAR(50),DOB DATE,Contact VARCHAR(50) UNIQUE,Address VARCHAR(50),S_engineering FLOAT,DBMS FLOAT,O_system FLOAT,N_method FLOAT,S_language FLOAT);

CREATE TABLE adm_info (aid INT AUTO_INCREMENT PRIMARY KEY,username VARCHAR(50),pasword VARCHAR(50));

CREATE TABLE attendance (att_id INT AUTO_INCREMENT,ID VARCHAR(50),dates DATE,std_status VARCHAR(50),PRIMARY KEY(att_id, ID),FOREIGN KEY(ID) REFERENCES std_info(ID));